### ISSUE TITLE
Does not work in Java 9 with modules enabled

### ISSUE THREAD

**Issue by emmettl** [opentracing-contrib/java-jms#10]
Hi there, currently if you try and use this in Java 9+ with modules enabled, the JVM fails to start.
`java.lang.module.FindException: Unable to derive module descriptor for C:\dev\maven\io\opentracing\contrib\opentracing-jms-1\0.0.5\opentracing-jms-1-0.0.5.jar
Caused by: java.lang.IllegalArgumentException: opentracing.jms.1: Invalid module name: '1' is not a Java identifier`
Could you please add an `Automatic-Module-Name` entry to the JAR manifest? 
Thanks

**Comment by malafeev** [comment]
will do

**Comment by malafeev** [comment]
fixed in version 0.0.7
