### ISSUE TITLE
JMS exceptions lose their traceIDs when logged

### ISSUE THREAD

**Issue by jnazander** [opentracing-contrib/java-jms#17]
I am using `opentracing-jms` to pass the `traceId` to `@JMSListener` methods. I'm also using [brave-context-slf4j](https://github.com/openzipkin/brave/tree/master/context/slf4j) to write tracing information to the MDC, so that any exception thrown will contain the traceId when logged (in Graylog).

So far it works fine, any exceptions caught and logged inside `@JMSListener` methods also have their `traceId` written to the `MDC` and logged.

Now, when an exception is not caught inside the `@JMSListener` method, then things don't go so well. It gets propagated up the call stack of the JMS listener thread and gets seen by `TracingMessageListener`, which clears the tracing context and lets the exception propagate further. So, when it's finally caught by Spring's `TracingMessagingMessageListenerAdapter` - the tracing context/MDC is already empty and the exception gets written without any tracing into.

So any JMS exceptions not explicitly caught will not contain the tracing info, which is the main reason of me using tracing in the first place.

I cannot simply extend the functionality of `TracingMessageListener` to catch the exception instead, because it's not a bean and is created explicitly in `TracingMessagingMessageListenerAdapter`, which is itself explicitly created in `TracingJmsListenerEndpointRegistry` (it's a long chain of inner private classes).

So with such a lack of extendability, I don't see any simple fix for this situation. While I understand that you can't simply change you code to catch all exceptions in `TracingMessageListener` instead of letting them propagate, what I would suggest in the future is to at least make `TracingMessageListener` and `TracingMessagingMessageListenerAdapter` into beans, to allow extendability.

I have already tried to use Spring AOP to wrap all `@JMSListener` methods inside try-catch statements that log any exceptions before the tracing context is closed. It _does_ work, but _ONLY_ with exceptions thrown _within_ `@JMSListener` methods. Anything thrown before that (e.g. by the message deserializer) will still be logged without any trace ID. And it's impossible to wrap any of those internal methods inside the stack trace because none of them are beans. 

Here is an example where a deserialization exceptions happens. Let's look at the stack trace, and which class can be extended to catch the exception before the tracing context closes:

> com.fasterxml.jackson.core.JsonParseException: Unexpected character ('d' (code 100)): was expecting a colon to separate field name and value
>  at [Source: (String)"{example}"; line: 2, column: 11],
> 	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:118)  **<-- not a bean**
> 	at org.springframework.jms.listener.adapter.MessagingMessageListenerAdapter.onMessage(MessagingMessageListenerAdapter.java:77)  **<-- not a bean**
> 	at io.opentracing.contrib.jms.spring.TracingJmsListenerEndpointRegistry$TracingMessagingMessageListenerAdapter.onMessageInternal(TracingJmsListenerEndpointRegistry.java:113)  **<-- not a bean, it's a private inner class**
> 	at io.opentracing.contrib.jms.spring.TracingJmsListenerEndpointRegistry$TracingMessagingMessageListenerAdapter.access$200(TracingJmsListenerEndpointRegistry.java:97)  **<-- not a bean, it's a private inner class**
> 	at io.opentracing.contrib.jms.spring.TracingJmsListenerEndpointRegistry$TracingMessagingMessageListenerAdapter$1.onMessage(TracingJmsListenerEndpointRegistry.java:105)  **<-- not a bean, it's a private inner class**
> 	at io.opentracing.contrib.jms.common.TracingMessageListener.onMessage(TracingMessageListener.java:41)**<-- this is where the tracing context initialization starts & stops, so everything further down the call stack will not have the trace ID. This is also not a bean.**
> 	at io.opentracing.contrib.jms.spring.TracingJmsListenerEndpointRegistry$TracingMessagingMessageListenerAdapter.onMessage(TracingJmsListenerEndpointRegistry.java:108) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.AbstractMessageListenerContainer.doInvokeListener(AbstractMessageListenerContainer.java:736) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.AbstractMessageListenerContainer.invokeListener(AbstractMessageListenerContainer.java:696) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.AbstractMessageListenerContainer.doExecuteListener(AbstractMessageListenerContainer.java:674) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.doReceiveAndExecute(AbstractPollingMessageListenerContainer.java:318) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.AbstractPollingMessageListenerContainer.receiveAndExecute(AbstractPollingMessageListenerContainer.java:257) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.invokeListener(DefaultMessageListenerContainer.java:1189) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.executeOngoingLoop(DefaultMessageListenerContainer.java:1179) **<-- no trace context anymore**
> 	at org.springframework.jms.listener.DefaultMessageListenerContainer$AsyncMessageListenerInvoker.run(DefaultMessageListenerContainer.java:1076) **<-- no trace context anymore**
> 	at java.lang.Thread.run(Thread.java:748) **<-- no trace context anymore**
> 

So as we can see, none of the trace context-containing classes could be extended.

**Comment by malafeev** [comment]
@jnazander would you like to submit a PR?

**Comment by jnazander** [comment]
@malafeev yes, sure.

**Comment by malafeev** [comment]
PR merged. 
@jnazander can be issue closed?

**Comment by jnazander** [comment]
Thank! Yes, you can close it now.

**Comment by malafeev** [comment]
fix will be available in version 0.0.10
