### ISSUE TITLE
Wrong boolean propagation

### ISSUE THREAD

**Issue by ancore** [opentracing-contrib/java-jms#35]
When creating a `TracingMessageConsumer`, the member `traceInLog` is provided to the constructor that expects `proxyMessage`. There are a few occurences of that.

https://github.com/opentracing-contrib/java-jms/blob/ed6326068e12d14f40631cd95563b21d44941085/opentracing-jms-2/src/main/java/io/opentracing/contrib/jms2/TracingSession.java#L145

**Comment by malafeev** [comment]
fixed via #36
