### ISSUE TITLE
TracingMessageProducer creates a new span not following current active span

### ISSUE THREAD

**Issue by hanson76** [opentracing-contrib/java-jms#37]
TracingMessageProducer uses TracingMessageUtils.buildAndInjectSpan to build a new span that is supposed to follow any currently active span.
The problem is that TracingMessageUtils.buildAndInjectSpan is using TracingMessageUtils.extract(message, tracer)
to try to extract current span from the message that is about to be sent or the current active span if the message does not include a span. 

BraveTracer will return a SpanContext on line 75 in  TracingMessageUtils even if the message does not include any headers for a span. 
The if statement on line 77 will then be true and the spanContext is returned. 
The spanContext returned by tracer.extract(...) will return null on calling toTraceId() and toSpanId()
The correct solution is to have the if statement on line 77 check
 if (spanContext != null && spanContext.toTraceId() != null && spanContext.toSpanId() != null)

**Comment by malafeev** [comment]
@hanson76 would you like to submit PR as you already have a fix?

**Comment by hanson76** [comment]
Sure

**Comment by malafeev** [comment]
fixed via #38
