### ISSUE TITLE
TracingConnectionFactory

### ISSUE THREAD

**Issue by berserkk** [opentracing-contrib/java-jms#39]
The library lacks `TracingConnectionFactory` class for tracing `ConnectionFactory`.

You're creating `TracingConnection` only in the one place:

https://github.com/opentracing-contrib/java-jms/blob/3aa4af830745624e9bb593e6bd6b6a08e6bddbcc/opentracing-jms-spring/src/main/java/io/opentracing/contrib/jms/spring/TracingJmsTemplate.java#L47-L50

Where `super.createConnection()` uses `ConnectionFactory` under the hood.

So, in case of `JmsTemplate` tracing will work properly. But in all other cases not. I've noticed this issue when was trying to use [DefaultMessageListenerContainer](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/jms/listener/DefaultMessageListenerContainer.html) and it didn't work well. It uses `Connection`s, where correct behavior is to use `TracingConnection`s.

Instrumentation based on `ConnectionFactory` seems to be more correct approach (it's also used in [Brave](https://github.com/openzipkin/brave/blob/21eb86717b7c75f6b2ae6c3c0cefb3b7e4bd3a6e/instrumentation/jms/README.md#setup), for example).

**Comment by malafeev** [comment]
@berserkk please submit a PR for adding `TracingConnectionFactory` if you are interested in it.

**Comment by berserkk** [comment]
@malafeev I'll try to do PR in the nearest time.

**Comment by berserkk** [comment]
@malafeev created PR, please review.

**Comment by berserkk** [comment]
Solved with #40.
