### ISSUE TITLE
Context not propagating

### ISSUE THREAD

**Issue by redijedi** [opentracing-contrib/java-jms#4]
I've run into difficulties getting the context to propagate across message boundaries. In dumping the received message on the `TracingMessageConsumer` end I can see that there is trace info in the message properties:
```
properties = {uber_$dash$_trace_$dash$_id=fb4fa660be8c6a8d:111832632e264b74:fb4fa660be8c6a8d:1},
```
The tracer records a span with the name `jms-send`. However, traced code within the message listener does not create a span. The message consumer is of type `TracingMessageConsumer` and it is set with a `TracingMessageListener` via the `setMessageListener` method. 

The code all executes, but nothing from `onMessage` on down ever gets traced. Thoughts?

**Comment by malafeev** [comment]
@redijedi  could you create test for that to reproduce?

**Comment by zhangzhenhuajack** [comment]
is project not to used?

**Comment by malafeev** [comment]
I have no idea how to reproduce this issue. I think something wrong in user's setup.
I think issue should be closed if no more clarifications for user.

**Comment by tedsuo** [comment]
Hi @redijedi, if you come back and are still having this issue, please reopen this ticket. Thanks!
