### ISSUE TITLE
Use different operation names for consumers and listeners

### ISSUE THREAD

**Issue by berserkk** [opentracing-contrib/java-jms#41]
It's possible to have a case where `TracingMessageConsumer` and `TracingMessageListener` are used together (e.g. [AbstractPollingMessageListenerContainer](https://github.com/spring-projects/spring-framework/blob/dc6f63f610ab0278c8c9d2c5c7cbbebb9928ec91/spring-jms/src/main/java/org/springframework/jms/listener/AbstractPollingMessageListenerContainer.java#L303-L319) from Spring).

It produces spans like these:

![Spans](https://user-images.githubusercontent.com/3935276/91914951-99b37000-ecb9-11ea-9263-f0a9890d3df0.png)

`jms-receive` from consumer and listener look a bit confusing. I propose to rename operation name for listener to `jms-on-message`.

I've checked [related code](https://github.com/openzipkin/brave/blob/c7fdf729f9e143a3cac3e52a68b338cdc91825a3/instrumentation/jms/src/main/java/brave/jms/TracingMessageListener.java#L88-L113) in Brave, they also use different operation names for consumer (`receive`) and listener (`on-message`).

What do you think about it? If you're ok with that, I can create PR.

**Comment by malafeev** [comment]
@berserkk PR is welcome

**Comment by berserkk** [comment]
Solved with #42.
