### ISSUE TITLE
TracingJMSConsumer implementation

### ISSUE THREAD

**Issue by stgiaf** [opentracing-contrib/java-jms#43]
Hello, 
Shouldn't there be also a TracingJMSConsumer for JMS 2?
It seems that the TracingConsumer is not compatible with JMSConsumer from JMS 2, so cannot be used with JMS 2 implementations.

**Comment by berserkk** [comment]
@stgiaf, hey. `TracingJMSConsumer` was added in #40 and is available from `0.1.10` version.

**Comment by stgiaf** [comment]
Hello @berserkk ,
Thanks, you are right. Changed the version and the class is available now.
